import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Rizq Ramadhan's Blog",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={"text-white font-mono bg-gradient-to-tr from-neutral-700 to-slate-700"}>{children}</body>
        </html>
    );
}
