import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Rizq Ramadhan's Blog",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={"m-0 p-0 text-white font-mono bg-black"}>
                {children}
            </body>
        </html>
    );
}
